import { BudgetData, Category, Transaction, Currency } from './types';

export const COLORS = {
  primary: '#1A936F',
  secondary: '#FEBB46',
  danger: '#F05654',
  grey: '#A4A4AB',
  background: '#F9F8FB',
  white: '#FFFFFF',
  text: '#050315',
  lightPurple: '#DEDCFF',
};

export const CURRENCIES: Currency[] = [
  { code: 'BDT', symbol: '৳', name: 'Bangladeshi Taka' },
  { code: 'USD', symbol: '$', name: 'US Dollar' },
  { code: 'MYR', symbol: 'RM', name: 'Malaysian Ringgit' },
  { code: 'EUR', symbol: '€', name: 'Euro' },
  { code: 'GBP', symbol: '£', name: 'British Pound' },
  { code: 'INR', symbol: '₹', name: 'Indian Rupee' },
  { code: 'SAR', symbol: '﷼', name: 'Saudi Riyal' },
  { code: 'AED', symbol: 'د.إ', name: 'UAE Dirham' },
];

export const TRANSLATIONS = {
  bn: {
    appName: 'আয়ব্যয়',
    hello: 'হ্যালো!',
    monthlyBudget: 'মাসিক বাজেট',
    remaining: 'অবশিষ্ট',
    income: 'আয়',
    expense: 'ব্যয়',
    topSpendings: 'শীর্ষ ব্যয়',
    serviceTitle: 'আপনার ব্যবসার জন্য সেরা পরিষেবা পান',
    learnMore: 'আরও জানুন',
    home: 'হোম',
    stats: 'পরিসংখ্যান',
    sync: 'সংযুক্ত',
    goal: 'বাজেট',
    toggleLang: 'English',
    addTransaction: 'নতুন লেনদেন',
    title: 'শিরোনাম',
    amount: 'পরিমাণ',
    category: 'বিভাগ',
    date: 'তারিখ',
    type: 'ধরণ',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    selectCategory: 'বিভাগ নির্বাচন করুন',
    history: 'লেনদেনের ইতিহাস',
    edit: 'সম্পাদনা',
    delete: 'মুছে ফেলুন',
    noTransactions: 'কোন লেনদেন নেই',
    all: 'সব',
    budgetGoal: 'বাজেট লক্ষ্য',
    setGoal: 'লক্ষ্য নির্ধারণ',
    spentOf: 'ব্যয়',
    categoryBudget: 'বিভাগীয় বাজেট',
    weekly: 'সাপ্তাহিক',
    monthly: 'মাসিক',
    yearly: 'বার্ষিক',
    spendingPattern: 'ব্যয়ের ধরণ',
    budget: 'অ্যাকাউন্ট',
    accounts: 'অ্যাকাউন্ট',
    cash: 'নগদ',
    bank: 'ব্যাংক/কার্ড',
    mobile: 'মোবাইল ওয়ালেট',
    addAccount: 'অ্যাকাউন্ট যোগ করুন',
    accountName: 'অ্যাকাউন্টের নাম',
    balance: 'ব্যালেন্স',
    selectAccount: 'অ্যাকাউন্ট নির্বাচন করুন',
    currency: 'মুদ্রা',
    selectCurrency: 'মুদ্রা নির্বাচন করুন',
    defaultCurrency: 'ডিফল্ট মুদ্রা',
    about: 'আমাদের সম্পর্কে',
    contact: 'যোগাযোগ',
    terms: 'শর্তাবলী',
    privacy: 'গোপনীয়তা নীতি',
    security: 'নিরাপত্তা',
    version: 'ভার্সন',
    writeName: 'আপনার নাম লিখুন',
    noAccounts: 'কোন অ্যাকাউন্ট নেই',
    welcome: 'স্বাগতম',
    manageCategories: 'বিভাগ পরিচালনা করুন',
    editCategory: 'বিভাগ সম্পাদনা করুন',
    deleteCategory: 'বিভাগ মুছে ফেলুন',
    newCategory: 'নতুন বিভাগ',
    uncategorized: 'অশ্রেণীবদ্ধ',
  },
  en: {
    appName: 'AyByay',
    hello: 'Hello!',
    monthlyBudget: 'Monthly Budget',
    remaining: 'Remaining',
    income: 'Income',
    expense: 'Expense',
    topSpendings: 'Top Spendings',
    serviceTitle: 'Get the best services for your business',
    learnMore: 'Learn More',
    home: 'Home',
    stats: 'Stats',
    sync: 'Sync',
    goal: 'Budget',
    toggleLang: 'বাংলা',
    addTransaction: 'Add Transaction',
    title: 'Title',
    amount: 'Amount',
    category: 'Category',
    date: 'Date',
    type: 'Type',
    save: 'Save',
    cancel: 'Cancel',
    selectCategory: 'Select Category',
    history: 'Transaction History',
    edit: 'Edit',
    delete: 'Delete',
    noTransactions: 'No transactions yet',
    all: 'All',
    budgetGoal: 'Budget Goal',
    setGoal: 'Set Goal',
    spentOf: 'spent of',
    categoryBudget: 'Category Budget',
    weekly: 'Weekly',
    monthly: 'Monthly',
    yearly: 'Yearly',
    spendingPattern: 'Spending Pattern',
    budget: 'Account',
    accounts: 'Accounts',
    cash: 'Cash',
    bank: 'Bank/Card',
    mobile: 'Mobile Wallet',
    addAccount: 'Add Account',
    accountName: 'Account Name',
    balance: 'Balance',
    selectAccount: 'Select Account',
    currency: 'Currency',
    selectCurrency: 'Select Currency',
    defaultCurrency: 'Default Currency',
    about: 'About Us',
    contact: 'Contact Us',
    terms: 'Terms & Conditions',
    privacy: 'Privacy Policy',
    security: 'Security',
    version: 'Version',
    writeName: 'Write your name',
    noAccounts: 'No accounts yet',
    welcome: 'Welcome',
    manageCategories: 'Manage Categories',
    editCategory: 'Edit Category',
    deleteCategory: 'Delete Category',
    newCategory: 'New Category',
    uncategorized: 'Uncategorized',
  },
};

export const CATEGORIES: Category[] = [
  { id: 'food', name: { bn: 'খাবার', en: 'Food' }, icon: 'Utensils' },
  { id: 'shopping', name: { bn: 'কেনাকাটা', en: 'Shopping' }, icon: 'ShoppingCart' },
  { id: 'fuel', name: { bn: 'জ্বালানী', en: 'Fuel' }, icon: 'Fuel' },
  { id: 'invest', name: { bn: 'বিনিয়োগ', en: 'Invest' }, icon: 'TrendingUp' },
];
